mod 'puppet-nginx', '0.14.0'
mod 'puppetlabs-stdlib', '5.1.0'
mod 'puppetlabs-concat', '5.1.0'
mod 'pltraining-dockeragent', '0.0.16'
mod 'garethr-docker'
mod 'puppetlabs-apt'
mod 'puppetlabs-translate'
mod 'stahnma-epel'
